#!/bin/bash
# 📚 GUÍA DE SCRIPTS DE MANTENIMIENTO
# Sistema de auditoría, sincronización y coherencia del Design System

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          📚 GUÍA DE SCRIPTS DE MANTENIMIENTO               ║"
echo "║              Design System v2.2.0                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 SCRIPTS DISPONIBLES"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  MANTENIMIENTO INTEGRAL (RECOMENDADO)"
echo "   ► Ejecuta: python3 scripts/maintain.py"
echo "   ✓ Audita todo el sistema"
echo "   ✓ Sincroniza tokens entre 4 fuentes"
echo "   ✓ Genera componentes faltantes"
echo "   ✓ Valida coherencia"
echo "   ✓ Limpia y organiza"
echo "   Opciones:"
echo "   --full          Mantenimiento completo (default)"
echo "   --audit         Solo auditoría"
echo "   --sync          Solo sincronización"
echo "   --generate      Solo generación de componentes"
echo "   --validate      Solo validación"
echo "   --dry-run       Simular sin cambios"
echo "   --verbose       Salida detallada"
echo ""

echo "2️⃣  AUDITORÍA COMPLETA"
echo "   ► Ejecuta: python3 scripts/audit-complete.py"
echo "   ✓ Audita sincronización de tokens (4 fuentes)"
echo "   ✓ Verifica Foundations (8 categorías)"
echo "   ✓ Valida componentes documentados"
echo "   ✓ Verifica patrones"
echo "   ✓ Audita WCAG AA compliance"
echo "   ✓ Genera reporte JSON"
echo "   Opciones:"
echo "   --verbose       Salida detallada"
echo "   --export        Exportar reporte a AUDIT-REPORT.json"
echo ""

echo "3️⃣  SINCRONIZACIÓN DE TOKENS"
echo "   ► Ejecuta: python3 scripts/sync-tokens.py"
echo "   ✓ CSS → JSON (tokens.css → tokens.json)"
echo "   ✓ JSON → JavaScript (TOKEN_META en main.js)"
echo "   ✓ Tokens → Manifest (component-manifest.json)"
echo "   ✓ Verifica coherencia entre 4 fuentes"
echo "   Opciones:"
echo "   --all           Sincronizar todo (default)"
echo "   --css-to-json   Solo CSS → JSON"
echo "   --json-to-js    Solo JSON → JavaScript"
echo "   --dry-run       Simular sin cambios"
echo "   --verbose       Salida detallada"
echo ""

echo "4️⃣  GENERACIÓN DE COMPONENTES FALTANTES"
echo "   ► Ejecuta: python3 scripts/generate-components.py"
echo "   ✓ Detecta componentes faltantes"
echo "   ✓ Genera plantillas basadas en AGENT-CONTRACT"
echo "   ✓ Incluye todas las secciones necesarias"
echo "   ✓ Respeta estructura estándar"
echo "   Opciones:"
echo "   --all                    Generar todos los faltantes"
echo "   --component NAME         Generar componente específico"
echo "   --preview                Vista previa sin crear"
echo "   --dry-run                Simular sin crear archivos"
echo ""

echo "5️⃣  REPORTES Y DASHBOARDS"
echo "   ► Ejecuta: python3 scripts/report.py"
echo "   ✓ Reporte ejecutivo del sistema"
echo "   ✓ Cobertura de documentación"
echo "   ✓ Dashboard de salud del sistema"
echo "   ✓ Puntuaciones por área"
echo "   Opciones:"
echo "   --executive     Reporte ejecutivo (default)"
echo "   --coverage      Reporte de cobertura"
echo "   --health        Dashboard de salud"
echo "   --json          Exportar como JSON"
echo ""

echo "📊 FLUJOS RECOMENDADOS"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "✅ FLUJO DIARIO (5 minutos)"
echo "   python3 scripts/maintain.py --validate"
echo ""

echo "✅ FLUJO SEMANAL (15 minutos)"
echo "   python3 scripts/maintain.py --full"
echo ""

echo "✅ FLUJO ANTES DE RELEASE"
echo "   python3 scripts/audit-complete.py --export"
echo "   python3 scripts/sync-tokens.py --all"
echo "   python3 scripts/report.py --executive"
echo "   python3 scripts/validate-coherence.py"
echo ""

echo "✅ FLUJO DE DEBUGGING"
echo "   python3 scripts/audit-complete.py --verbose"
echo "   python3 scripts/sync-tokens.py --dry-run"
echo "   python3 scripts/report.py --health"
echo ""

echo "📁 ESTRUCTURA DE SCRIPTS"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "scripts/"
echo "  ├─ validate-coherence.py       (Validador existente)"
echo "  ├─ audit-complete.py           (🆕 Auditoría exhaustiva)"
echo "  ├─ sync-tokens.py              (🆕 Sincronización de tokens)"
echo "  ├─ generate-components.py      (🆕 Generación de componentes)"
echo "  ├─ maintain.py                 (🆕 Orquestador maestro)"
echo "  ├─ report.py                   (🆕 Reportes y dashboards)"
echo "  └─ README.sh                   (Esta guía)"
echo ""

echo "📋 ARCHIVOS GENERADOS"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Reportes automáticos:"
echo "  • AUDIT-REPORT.json            (Auditoría con detalles)"
echo "  • MAINTENANCE-REPORT.json      (Resumen de mantenimiento)"
echo "  • EXECUTIVE-REPORT.md          (Reporte ejecutivo)"
echo "  • COVERAGE-REPORT.md           (Cobertura de documentación)"
echo "  • HEALTH-DASHBOARD.md          (Salud del sistema)"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "❌ Error: 'No module named json'"
echo "   ✓ Los módulos json, re, pathlib vienen con Python 3"
echo "   ✓ Verifica: python3 --version"
echo ""

echo "❌ Error: 'Permission denied'"
echo "   ✓ Permisos: chmod +x scripts/*.py"
echo ""

echo "❌ Tokens no sincronizados"
echo "   ✓ Ejecuta: python3 scripts/sync-tokens.py --all"
echo ""

echo "⚠️  Warning: Componentes faltantes"
echo "   ✓ Genera: python3 scripts/generate-components.py --all"
echo ""

echo "🎓 EJEMPLOS COMPLETOS"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "Ejemplo 1: Auditoría rápida"
echo "  \$ python3 scripts/audit-complete.py"
echo ""

echo "Ejemplo 2: Sincronizar tokens"
echo "  \$ python3 scripts/sync-tokens.py --all --verbose"
echo ""

echo "Ejemplo 3: Ver qué pasaría si genero componentes"
echo "  \$ python3 scripts/generate-components.py --all --dry-run"
echo ""

echo "Ejemplo 4: Mantenimiento completo sin cambios"
echo "  \$ python3 scripts/maintain.py --full --dry-run"
echo ""

echo "Ejemplo 5: Reporte de salud del sistema"
echo "  \$ python3 scripts/report.py --health"
echo ""

echo "📞 REFERENCIA RÁPIDA"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Hacer auditoría:             python3 scripts/audit-complete.py"
echo "Sincronizar tokens:          python3 scripts/sync-tokens.py --all"
echo "Generar componentes:         python3 scripts/generate-components.py --all"
echo "Validar coherencia:          python3 scripts/validate-coherence.py"
echo "Reporte ejecutivo:           python3 scripts/report.py --executive"
echo "Dashboard de salud:          python3 scripts/report.py --health"
echo "Mantenimiento completo:      python3 scripts/maintain.py"
echo "Mantenimiento (dry-run):     python3 scripts/maintain.py --dry-run"
echo ""

echo "✅ Para más información:"
echo "   - Documentación: 00-fundamentos/FOUNDATIONS.md"
echo "   - Tokens: 01-tokens/README.md"
echo "   - Componentes: 02-componentes/"
echo "   - Contratos: 05-agentes/AGENT-CONTRACT.md"
echo ""
